### ISSUE TITLE
package-lock.yml does not recognize keys `packages` and `sha1_hash`

### ISSUE THREAD

**Issue by aleix-cd** [dbt-labs/dbt-jsonschema#167]
<img width="545" alt="image" src="https://github.com/user-attachments/assets/ae4f081e-ec28-40b0-b397-f004e62fc67e">

Both `packages` and `sha1_hash` YAML keys from the `package-lock.yml` file are not being identified as allowed.

I've checked, and I believe these are not included anywhere in the `dbt-jsonschema` project.

Should these be on their own JSON file in the repo, specifically for the `package-lock` file?

Happy to contribute, if needed

**Comment by joellabes** [comment]
Hey @aleix-cd! Since package-lock is generated by dbt itself instead of being human-made file, I don't think we need a file for it. I think instead you'll want to add it as an exclusion to the dbt_yml_files in your `settings.json` file: 

```
{    
    "yaml.schemas": {
        "https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/latest/dbt_yml_files-latest.json": [
            "/**/*.yml",
            "!profiles.yml",
            "!dbt_project.yml",
            "!packages.yml",
            "!selectors.yml",
            "!profile_template.yml",
            "!package-lock.yml"
        ],
```

adding the final line here should see you right! I'll update the readme accordingly

**Comment by aleix-cd** [comment]
that was super useful, thanks a lot @joellabes!
